field: 09b22790-fc34-440b-89f6-36254ec3cbfa # Flexible Content
fieldLayouts:
  551eea73-02a6-480a-b2cf-294e61f5d217:
    tabs:
      -
        elements:
          -
            fieldUid: 75b63475-a9cc-45aa-b67e-de085416e457 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: f2f7b225-26f3-426a-8678-c089918dacf9 # Year
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 75c64953-510f-4b4b-997c-5e015e3cb084 # Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: baa13c65-0a57-43bf-8c5b-5dc010d1cd1c # Songs
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f44d3203-84a7-4d9f-8cfa-cf2cbb0a2316 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  75b63475-a9cc-45aa-b67e-de085416e457: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  75c64953-510f-4b4b-997c-5e015e3cb084: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  baa13c65-0a57-43bf-8c5b-5dc010d1cd1c: # Songs
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: songs
    instructions: ''
    name: Songs
    searchable: false
    settings:
      addRowLabel: 'Add a song'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - '60'
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - ID
                -
                  - handle
                  - id
                -
                  - width
                  - '40'
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - 'Song title'
            -
              - col3
              - 'Song ID'
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  f2f7b225-26f3-426a-8678-c089918dacf9: # Year
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: year
    instructions: ''
    name: Year
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 1990
      prefix: null
      previewCurrency: ''
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  f44d3203-84a7-4d9f-8cfa-cf2cbb0a2316: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
        - video
      defaultUploadLocationSource: 'volume:c59415d9-dcf6-439b-8d6a-146665a862e6' # Local
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:c59415d9-dcf6-439b-8d6a-146665a862e6' # Local
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: milestone
name: Milestone
sortOrder: 1
