fieldLayouts:
  d03205f5-9d96-4497-a345-c22567b54a60:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6942b6db-1e4b-4258-8a53-45ad3f540366
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eb252ecb-0d63-4fff-aca5-fd61b5e729d2 # Writer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38d16b1e-3a85-460f-9de1-503cf89f6ef1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 07f98a9a-ab5a-4984-b782-5f308a478bf0 # Fiction?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 836b1725-a991-44b7-9d9b-1334bc6d65a4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f5084cc-0fc8-472f-bcdf-9c5db26a3001 # Featured image
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62a98f3a-15ec-47cd-b145-49377384f243
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69d1b4e6-4981-4ef6-ac2d-34691c18c906 # Date read
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: addb321c-d6bf-4e83-ac38-3207a110bce5
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb4f3d4d-8a2c-4b6c-a0a7-0861b1d7a09d # Publication year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d924a0b4-e77a-4da3-ab81-6e186101ad46
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4ff40bad-6fd2-4bdc-9feb-65a47931998d # Length
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51f7bf35-b708-473a-8383-855d06ff2545
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 52047e94-5988-47b4-b9b5-6e061b5c2b49 # Medium
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3ca9891-9dc3-40b6-b852-985f16950cc3
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0be8bfd9-86e6-48dd-8142-9020d3adb154 # Rating
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 194ffd06-734d-4c06-8825-7f1ced3ef27e
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-11T22:40:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9bb7b114-ed0e-4ebe-bf8f-9f5c8a3b64de # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfeb5a2f-0b06-448e-b91f-47c465d595b3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 335adbae-7914-48f2-9fc2-5494eab9b34c
        userCondition: null
handle: books_default
hasTitleField: true
name: 'Books - Default'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
