color: null
fieldLayouts:
  551eea73-02a6-480a-b2cf-294e61f5d217:
    cardView:
      - 'layoutElement:88a4830b-e0ce-4ed2-94ff-fd913f9bbd27'
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 75b63475-a9cc-45aa-b67e-de085416e457
            handle: null
            instructions: null
            label: Heading
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88a4830b-e0ce-4ed2-94ff-fd913f9bbd27
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f2f7b225-26f3-426a-8678-c089918dacf9
            handle: null
            instructions: null
            label: Year
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 117ec339-98dd-4a55-bc6e-f1ff0591b80d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 75c64953-510f-4b4b-997c-5e015e3cb084
            handle: body
            instructions: null
            label: Body
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96a3b174-cea0-4815-b9ca-33d47ddc568e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: baa13c65-0a57-43bf-8c5b-5dc010d1cd1c
            handle: null
            instructions: null
            label: Songs
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7af28439-6e08-4898-9e2d-5a93c9f6987e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f44d3203-84a7-4d9f-8cfa-cf2cbb0a2316
            handle: null
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4960bba-c573-442d-80dd-b998e99bc5f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e8a801d0-1191-4788-b7ab-e604611f6a32
        userCondition: null
    thumbFieldKey: 'layoutElement:c4960bba-c573-442d-80dd-b998e99bc5f3'
handle: milestone
hasTitleField: false
icon: null
name: Milestone
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
