defaultPlacement: end
fieldLayouts:
  3abd3970-56db-4aca-948b-1055a43bc3f2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: writer
name: Writer
siteSettings:
  6dcb6011-4fe4-4cab-8aa4-2307909c8d66:
    hasUrls: true
    template: null
    uriFormat: 'writer/{slug}'
structure:
  maxLevels: 1
  uid: 2d7739db-01a8-4c18-9df0-a4136ce219ab
