defaultPlacement: end
fieldLayouts:
  3abd3970-56db-4aca-948b-1055a43bc3f2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: b4326f0c-2069-4710-8160-88c1b305dc95
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d2f95b40-d14e-47c3-a705-54d605e9f1fe # Gender
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcb1d9e6-208a-4be2-8abd-0ecf3cd40c37
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 758bbffe-2862-48ed-9e18-c7c7148fd932
        userCondition: null
    thumbFieldKey: null
handle: writer
name: Writer
siteSettings:
  6dcb6011-4fe4-4cab-8aa4-2307909c8d66: # Charles Harries
    hasUrls: true
    template: null
    uriFormat: 'writer/{slug}'
structure:
  maxLevels: 1
  uid: 2d7739db-01a8-4c18-9df0-a4136ce219ab
