baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-GB
name: 'Charles Harries'
primary: true
siteGroup: 72c0aa82-0cdf-4f69-9188-fea54b5c34a4 # Charles Harries
sortOrder: 1
