columnSuffix: mqwtrmyh
handle: body
instructions: null
name: Body
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 763fc5b6-7451-4ddc-969c-f16d0c2b6245 # S3
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options:
    __assoc__:
      -
        - htmlSupport
        -
          __assoc__:
            -
              - allow
              -
                -
                  __assoc__:
                    -
                      - attributes
                      - true
                    -
                      - key
                      - p
                -
                  __assoc__:
                    -
                      - attributes
                      - true
                    -
                      - key
                      - li
      -
        - removePlugins
        -
          - ImageEditor
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - code
    - superscript
    - blockQuote
    - insertImage
    - insertVideo
    - mediaEmbed
    - bulletedList
    - numberedList
    - horizontalLine
    - codeBlock
    - link
    - '|'
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
