columnSuffix: mqwtrmyh
contentColumnType: text
fieldGroup: 72753318-2e64-40d2-bbb0-f64f138ab9f7 # Common
handle: body
instructions: null
name: Body
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 763fc5b6-7451-4ddc-969c-f16d0c2b6245 # S3
  ckeConfig: 5ecf9283-524b-4a3f-a7a1-d27adb6f28e9 # Extended
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
