columnSuffix: null
handle: designations
instructions: null
name: Designations
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a designation'
  showSearchInput: true
  showSiteMenu: true
  source: 'taggroup:0dc92d8f-d943-4a05-b7c3-70f90413fb2b' # Designations
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
