columnSuffix: null
contentColumnType: string
fieldGroup: 72753318-2e64-40d2-bbb0-f64f138ab9f7 # Common
handle: featuredImage
instructions: ''
name: 'Featured image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:c59415d9-dcf6-439b-8d6a-146665a862e6' # Local
  defaultUploadLocationSubpath: ''
  limit: '2'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add a featured image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:c59415d9-dcf6-439b-8d6a-146665a862e6' # Local
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
