columnSuffix: null
handle: featuredImage
instructions: null
name: 'Featured image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:763fc5b6-7451-4ddc-969c-f16d0c2b6245' # S3
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: thumbs
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:763fc5b6-7451-4ddc-969c-f16d0c2b6245' # S3
  restrictedLocationSubpath: null
  selectionLabel: 'Add a featured image'
  showCardsInGrid: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:763fc5b6-7451-4ddc-969c-f16d0c2b6245' # S3
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
