columnSuffix: nvpnlhme
handle: fiction
instructions: null
name: 'Fiction?'
searchable: false
settings:
  default: true
  offLabel: Nonfiction
  onLabel: Fiction
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
