columnSuffix: nvpnlhme
contentColumnType: boolean
handle: fiction
instructions: null
name: 'Fiction?'
searchable: false
settings:
  default: true
  offLabel: Nonfiction
  onLabel: Fiction
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
