columnSuffix: null
contentColumnType: string
fieldGroup: 72753318-2e64-40d2-bbb0-f64f138ab9f7 # Common
handle: flexibleContent
instructions: ''
name: 'Flexible Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_flexiblecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
