columnSuffix: rzvlgzzn
contentColumnType: string(6)
handle: gender
instructions: null
name: Gender
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Male
        -
          - value
          - male
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Female
        -
          - value
          - female
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Other
        -
          - value
          - other
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
