columnSuffix: zcmocqse
contentColumnType: string(255)
handle: githubLink
instructions: null
name: 'GitHub Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
