columnSuffix: mxxqdoes
contentColumnType: string
handle: meta
instructions: null
name: Meta
searchable: false
settings:
  entryTypes:
    - faf9797f-b632-4e47-8a8b-e676d6cd03f2 # About the walk
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
