columnSuffix: mxxqdoes
contentColumnType: string
fieldGroup: 72753318-2e64-40d2-bbb0-f64f138ab9f7 # Common
handle: meta
instructions: ''
name: Meta
searchable: false
settings:
  contentTable: '{{%matrixcontent_meta}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
