columnSuffix: null
handle: mountains
instructions: null
name: Mountains
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a mountain'
  showSearchInput: true
  showSiteMenu: false
  source: 'taggroup:59ce730c-2dc9-446d-bd6c-828a58fedaa9' # Mountains
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
