columnSuffix: null
handle: orientation
instructions: null
name: Orientation
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Landscape
        -
          - value
          - landscape
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Portrait
        -
          - value
          - portrait
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
