columnSuffix: qkpdkevb
contentColumnType: boolean
handle: showTitle
instructions: null
name: 'Show title?'
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
