columnSuffix: qkpdkevb
handle: showTitle
instructions: null
name: 'Show title?'
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
