columnSuffix: null
handle: strava
instructions: null
name: 'Meta - About the walk - Strava'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
