columnSuffix: hplecfpx
contentColumnType: string(1020)
handle: summary
instructions: null
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'This post is about...'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
