columnSuffix: hplecfpx
contentColumnType: string(1020)
fieldGroup: 72753318-2e64-40d2-bbb0-f64f138ab9f7 # Common
handle: summary
instructions: null
name: Summary
searchable: true
settings:
  byteLimit: null
  charLimit: 255
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'This post is about...'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
