columnSuffix: null
contentColumnType: string
handle: tags
instructions: null
name: Tags
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'taggroup:c1f54edf-7fb1-43d0-af35-bdf0579d236c' # Tags
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
