columnSuffix: null
handle: tags
instructions: null
name: Tags
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  source: 'taggroup:c1f54edf-7fb1-43d0-af35-bdf0579d236c' # Tags
  targetSiteId: null
  validateRelatedElements: true
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
