columnSuffix: null
contentColumnType: string
fieldGroup: 72753318-2e64-40d2-bbb0-f64f138ab9f7 # Common
handle: tags
instructions: ''
name: Tags
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'taggroup:c1f54edf-7fb1-43d0-af35-bdf0579d236c' # Tags
  sources: '*'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
