columnSuffix: yvcicctm
contentColumnType: string
fieldGroup: 72753318-2e64-40d2-bbb0-f64f138ab9f7 # Common
handle: writer
instructions: ''
name: Writer
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'taggroup:ad4febb7-733d-4e16-818e-aec623f4b582' # Writers
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
