columnSuffix: yvcicctm
handle: writer
instructions: null
name: Writer
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: 1
  defaultPlacement: end
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a writer'
  showSearchInput: true
  showSiteMenu: true
  source: 'group:8c4a8cd9-3f50-49e9-aed5-f46067c94fb9' # Writer
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
