dateModified: 1638834809
email:
  fromEmail: charles@harries.me
  fromName: 'Charles Harries'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0d74ed0f-b46b-4094-9038-b30e655c7b30: Default # Default
    6dcb6011-4fe4-4cab-8aa4-2307909c8d66: 'Charles Harries' # Charles Harries
    9bb7b114-ed0e-4ebe-bf8f-9f5c8a3b64de: Body # Body
    72c0aa82-0cdf-4f69-9188-fea54b5c34a4: 'Charles Harries' # Charles Harries
    75f81d9a-3f3c-4479-9949-7a535abd7e37: Stream # Stream
    98e705a6-d7c8-48c1-b096-b2deaf9283df: Local # Local
    526bb8da-d5c2-4a46-b9ac-a969de860ce5: Summary # Summary
    61727a0a-6742-4674-930c-0a3f6a9fe2a1: Default # Default
    071255ac-4fb5-404c-b125-46fa49417bc2: Posts # Posts
    72753318-2e64-40d2-bbb0-f64f138ab9f7: Common # Common
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Charles Harries'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
