fieldLayouts:
  b46bda5b-18bc-4735-af12-8b64ab8bf3cb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: cloudinary
hasUrls: true
name: Cloudinary
settings:
  apiKey: '521931841136364'
  apiSecret: 4cfeY1Q-zW8Nnl3-KvV1pN1ACKg
  cloudName: dnz9qbnn1
  overwrite: true
  subfolder: ''
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\cloudinary\Volume
url: 'https://res.cloudinary.com/dnz9qbnn1/image/upload/v1638906922/'
