defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4c827962-66cf-4542-b561-aa8650e5f2de # Books - Default
handle: books
maxAuthors: 1
minAuthors: 1
name: Books
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6dcb6011-4fe4-4cab-8aa4-2307909c8d66: # Charles Harries
    enabledByDefault: true
    hasUrls: true
    template: writing/_entry.twig
    uriFormat: 'books/{slug}'
type: channel
