defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 61727a0a-6742-4674-930c-0a3f6a9fe2a1 # Posts - Default
handle: posts
maxAuthors: 1
minAuthors: 1
name: Posts
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6dcb6011-4fe4-4cab-8aa4-2307909c8d66: # Charles Harries
    enabledByDefault: true
    hasUrls: true
    template: writing/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
