defaultPlacement: end
enableVersioning: true
handle: projects
name: Projects
propagationMethod: all
siteSettings:
  6dcb6011-4fe4-4cab-8aa4-2307909c8d66: # Charles Harries
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: 'projects/{slug}'
type: channel
