defaultPlacement: end
enableVersioning: true
entryTypes:
  - a13bbb59-bb25-4ea6-82ae-0b4cfa786aeb # Sam Posts - Default
handle: samPosts
maxAuthors: 1
name: 'Sam Posts'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6dcb6011-4fe4-4cab-8aa4-2307909c8d66: # Charles Harries
    enabledByDefault: true
    hasUrls: true
    template: sam-posts/_entry
    uriFormat: 'sam-posts/{slug}'
type: channel
