defaultPlacement: end
enableVersioning: true
handle: walks
name: Walks
propagationMethod: all
siteSettings:
  6dcb6011-4fe4-4cab-8aa4-2307909c8d66: # Charles Harries
    enabledByDefault: true
    hasUrls: true
    template: writing/_entry.twig
    uriFormat: 'walks/{slug}'
type: channel
